language: java
jdk:
    - oraclejdk8
before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
script:
    - ./gradlew build
    - mv ./build/distributions/helloworld-springboot.zip ./helloworld-springboot-$TRAVIS_BUILD_NUMBER.zip
    - aws s3 cp ./helloworld-springboot-$TRAVIS_BUILD_NUMBER.zip s3://demo-bucket-us-east-2-465010111800
after_success:
    - aws elasticbeanstalk create-application-version --application-name 'demo-app' --version-label "0.1.$TRAVIS_BUILD_NUMBER" --source-bundle S3Bucket="demo-bucket-us-east-2-465010111800",S3Key="helloworld-springboot-$TRAVIS_BUILD_NUMBER.zip"
    - aws elasticbeanstalk update-environment --application-name 'demo-app' --environment-id 'e-m3rq5hmndq' --version-label "0.1.$TRAVIS_BUILD_NUMBER"
